name: Changelog Reminder

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all commits are fetched

      - name: Check for CHANGELOG.md update
        id: changelog_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "CHANGELOG.md"; then
            echo "Changelog updated."
            echo "::set-output name=updated::true"
          else
            echo "Changelog not updated."
            echo "::set-output name=updated::false"
          fi

      - name: Post reminder comment
        if: steps.changelog_check.outputs.updated == 'false'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "⚠️ Please remember to update the CHANGELOG.md!"
          token: ${{ secrets.GITHUB_TOKEN }}
